Advogado/Controllers/TipoDocumentoController.cs
using Advogado.Data;
using Advogado.Helpers;
using Advogado.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Advogado.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class TipoDocumentoController : Controller
    {
        private readonly MainContext _db = new MainContext();        

        public ActionResult Index()
        {          
            var list = _db.TiposArquivos.ToList();
            return View(list);
        }

        public ActionResult Novo()
        {
            //bool existeGrupoTipoArquivo = _db.GruposTiposArquivos.Any(x => x.Ativo);
            //if (!existeGrupoTipoArquivo) return RedirectToAction("Index").Error("Por favor cadastre um grupo de tipo de documento antes de tentar cadastrar um tipo de documento!");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Novo(TipoArquivo model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                model.Modelo = string.Empty;
                if (model.ModeloArquivo != null && model.ModeloArquivo.ContentLength > 0) model = Anexar(model);
                model.Ativo = true;
                _db.TiposArquivos.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {               
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _db.TiposArquivos.Find(id);            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(TipoArquivo model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                var novo = _db.TiposArquivos.Find(model.TipoArquivoId);
                if (model.MantemMesmoModelo == false)
                {
                    model = Anexar(model);
                }                   
                else
                {
                    model.Modelo = novo.Modelo;
                }
                novo.Atualizar(model);
                _db.Entry(novo).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {                
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                var model = _db.TiposArquivos.Find(id);
                model.InverterAtivo();
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }

        public ActionResult ModeloArquivo()
        {
            return PartialView("_ModeloArquivo");
        }

        private TipoArquivo Anexar(TipoArquivo model)
        {
            int ByteSize = 1048576;
            int SizeInBytesMax = ByteSize * 10;
            var virtualPath = "~/Uploads/TipoArquivo";
            var allowedExtensions = new List<string> { ".pdf", ".docx", ".doc" };
            var tipoArquivo = new TipoArquivo();
            if (model.TipoArquivoId != 0) tipoArquivo = _db.TiposArquivos.Find(model.TipoArquivoId);
            if (model.ModeloArquivo != null && model.ModeloArquivo.ContentLength > 0)
            {
                int sizeByte = model.ModeloArquivo.ContentLength;
                if (!(sizeByte <= SizeInBytesMax)) throw new Exception("Limite de envio de arquivo atingido!");
                string extension = Path.GetExtension(model.ModeloArquivo.FileName);
                if (!allowedExtensions.Contains(extension.ToLower())) throw new Exception("Extensão não permitida");
                var physicalPath = Server.MapPath(virtualPath);
                if (!Directory.Exists(physicalPath)) Directory.CreateDirectory(physicalPath);
                if (!Directory.Exists(physicalPath)) throw new Exception($"Diretório {physicalPath} não existe!");
                string fileName = $"{Guid.NewGuid()}{extension}";
                string filePath = Path.Combine(physicalPath, fileName);
                if (model.TipoArquivoId != 0)
                {
                    var fileOld = Server.MapPath(tipoArquivo.Modelo);
                    if (System.IO.File.Exists(fileOld)) System.IO.File.Delete(fileOld);
                }
                model.ModeloArquivo.SaveAs(filePath);
                model.Modelo = $"{virtualPath}/{fileName}";
            }
            else if (model.TipoArquivoId != 0)
            {
                var fileOld = Server.MapPath(tipoArquivo.Modelo);
                if (System.IO.File.Exists(fileOld)) System.IO.File.Delete(fileOld);
                model.Modelo = string.Empty;
            }
            return model;
        }
    }
}

Advogado/Views/TipoDocumento/Editar.cshtml
@model Advogado.Models.TipoArquivo
@{
    ViewBag.Title = "Editar Documento";
}

@section scripts
{
    <script>
        $(document).on("change", "#ModeloArquivo", function () {
            $("#MantemMesmoModelo").val(false);
        });

        function RemoverArquivo() {
            $.ajax({
                method: "GET",
                url: $("#urls").data("urlModeloArquivo"),
                dataType: "html",
                success: function success(result) {
                    $("#div-modelo-arquivo").html(result);
                },
                error: function error(XMLHttpRequest, textStatus, errorThrown) {
                    console.log(XMLHttpRequest);
                    console.log(textStatus);
                    console.log(errorThrown);
                    swal("Mensagem", "Erro desconhecido!", "error");
                }
            });
        }
    </script>
}

<div id="urls" data-url-modelo-arquivo="@Url.Action("ModeloArquivo")"></div>

<div class="row small-spacing">
    <div class="col-lg-12 col-xs-12">
        <div class="box-content card white">
            <h4 class="box-title">@ViewBag.Title</h4>
            <div class="card-content">
                @using (Html.BeginForm("Editar", "TipoDocumento", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(m => m.TipoArquivoId)
                    @Html.Partial("_Form")
                }
            </div>
        </div>
    </div>
</div>

Advogado/Views/TipoDocumento/Index.cshtml
@using Advogado.Models
@model IEnumerable<TipoArquivo>
@{
    ViewBag.Title = "Documentos";
}

@section styles
{
    <link rel="stylesheet" href="~/Assets/plugin/datatables/media/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/plugin/datatables/extensions/Responsive/css/responsive.bootstrap.min.css">
}

@section scripts
{
    <script src="~/Assets/plugin/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/plugin/datatables/media/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/responsive.bootstrap.min.js"></script>
    <script src="~/Assets/scripts/datatables.demo.js"></script>
}

<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">@ViewBag.Title</h4>
        <div class="dropdown js__drop_down">
            <a href="@Url.Action("Novo")" class="btn btn-primary btn-circle btn-sm waves-effect waves-light"><i class="ico fa fa-plus"></i></a>
        </div>
        @Html.Partial("_Tabela")
    </div>
</div>

Advogado/Views/TipoDocumento/Novo.cshtml
@model Advogado.Models.TipoArquivo
@{
    ViewBag.Title = "Novo Documento";
}

<div class="row small-spacing">
    <div class="col-lg-12 col-xs-12">
        <div class="box-content card white">
            <h4 class="box-title">@ViewBag.Title</h4>
            <div class="card-content">
                @using (Html.BeginForm("Novo", "TipoDocumento", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.Partial("_Form")
                }
            </div>
        </div>
    </div>
</div>

Advogado/Views/TipoDocumento/TiposDeArquivosDoGrupo.cshtml
@using Advogado.Models
@model IEnumerable<TipoArquivo>
@{
    ViewBag.Title = "Ordenar Tipos do Documentos";
}

@section styles
{
    <link rel="stylesheet" href="~/Assets/plugin/datatables/media/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/plugin/datatables/extensions/Responsive/css/responsive.bootstrap.min.css">
    <link href="~/Assets/plugin/datatables/extensions/RowReorder/css/rowReorder.dataTables.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/Assets/plugin/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/plugin/datatables/media/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/responsive.bootstrap.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/RowReorder/js/dataTables.rowReorder.js"></script>

    <script>

        var table = $('#example').DataTable({
            rowReorder: true,
            select: true
        });

        table.on('row-reorder.dt', function (e, details, edit) {
            var lista = [];
            for (var i = 0; i < details.length; i++) {
                var perguntaId = $(details[i].node).data("perguntaId");
                lista.push({ "PerguntaId": perguntaId, "MudouDe": details[i].oldPosition, "Para": details[i].newPosition });
            }
            $.ajax({
                type: "POST",
                url: $('#example').data("url"),
                data: { lista: lista },
                success: function success(result) {
                    if (result.Error) {
                        swal("Mensagem", result.Error, "warning");
                    }
                },
                error: function error(XMLHttpRequest, textStatus, errorThrown) {
                    swal("Mensagem", errorThrown, "error");
                }
            });
        });
    </script>
}

<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">@ViewBag.Title</h4>
        @Html.Partial("_PerguntasGrupo")
    </div>
</div>

Advogado/Views/TipoDocumento/_Form.cshtml
@model Advogado.Models.TipoArquivo

@Html.AntiForgeryToken()

<div class="form-group col-md-12">
    @Html.LabelFor(m => m.Descricao)
    @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control", placeholder = "Informe a descrição" })
    @Html.ValidationMessageFor(m => m.Descricao)
</div>

<div class="form-group col-md-12">
    @Html.LabelFor(m => m.Observacao)
    @Html.TextBoxFor(m => m.Observacao, new { @class = "form-control", placeholder = "Informe a observação" })
    @Html.ValidationMessageFor(m => m.Observacao)
</div>

<div class="form-group col-md-12">
    @Html.LabelFor(m => m.Obrigatorio)
    @Html.DropDownListFor(model => model.Obrigatorio, new List<SelectListItem>()
    {
        new SelectListItem() { Text = "Sim", Value = "True" },
        new SelectListItem() { Text = "Não", Value = "False"}
    }, "Selecione...", new { @class = "form-control", @id = "Obrigatorio" })
    @Html.ValidationMessageFor(model => model.Obrigatorio)
</div>

<div class="form-group col-md-12" id="div-modelo-arquivo">
    @if (Model != null && !string.IsNullOrEmpty(Model.Modelo))
    {
        @Html.LabelFor(m => m.Modelo)
        <li class="list-group-item">
            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Clique para ver as opções</a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="@Url.Content(Model.Modelo)" target="_blank">Baixar arquivo de modelo</a></li>
                <li><a href="#" onclick="RemoverArquivo()">Remover arquivo de modelo</a></li>
            </ul>
        </li>
        <input type="hidden" id="MantemMesmoModelo" name="MantemMesmoModelo" value="True" />
    }
    else
    {
        @Html.Partial("_ModeloArquivo")
    }
</div>

<div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary btn-sm waves-effect waves-light">Confirmar</button>
    <a href="@Url.Action("Index")" class="btn btn-warning btn-sm waves-effect waves-light">Cancelar</a>
</div>

Advogado/Views/TipoDocumento/_ModeloArquivo.cshtml
<label>Modelo</label>
<input type="file" id="ModeloArquivo" name="ModeloArquivo">
<input type="hidden" id="MantemMesmoModelo" name="MantemMesmoModelo" value="False" />

Advogado/Views/TipoDocumento/_Tabela.cshtml
@using Advogado.Models
@model IEnumerable<TipoArquivo>

<table id="example" class="table table-responsive table-striped table-bordered display" style="width:100%">
    <thead>
        <tr>
            <th>Descrição</th>                      
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr @{ if (!item.Ativo) { @Html.Raw("style=\"background-color: #fdeef2\"")  ; } }>
            <td>@item.Descricao</td>     
            <td class="text-nowrap" width="10">
                <a class="btn btn-circle btn-info btn-sm" title="Editar" href="@Url.Action("Editar", new { id = item.TipoArquivoId })" data-togle="tooltip">
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                </a>
                <a class="btn btn-circle @(item.Ativo ? "btn-warning" : "btn-success") btn-sm" title="@(item.Ativo ? "Desativar" : "Ativar")" btn-sm" href="@Url.Action("Remover", new { id = item.TipoArquivoId })" data-togle="tooltip">
                    <i class="@(item.Ativo ? "fa fa-close" : "fa fa-check")" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>