Advogado/Models/Funcionario.cs
using System;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Script.Serialization;

namespace Advogado.Models
{
    public class Funcionario
    {
        public int FuncionarioId { get; set; }

        [Display(Name = "Nome")]
        [MinLength(1, ErrorMessage = "Mínimo 1 caractere")]
        [MaxLength(255, ErrorMessage = "Máximo 255 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Nome { get; set; }

        [Display(Name = "CPF")]
        [MinLength(1, ErrorMessage = "Mínimo 1 caractere")]
        [MaxLength(14, ErrorMessage = "Máximo 14 caracteres")]
        [Required(ErrorMessage = "Campo obrigatório")]
        public string Cpf { get; set; }

        public string Senha { get; set; }

        public Perfil Perfil { get; set; }

        public bool Ativo { get; set; }

        public bool ValidarUsuarioSenha(string hashCorreto)
        {
            var hashsenhaDigitada = GerarMd5(Senha);
            if (hashCorreto == hashsenhaDigitada) return true;
            return false;
        }

        public string GerarMd5(string senha)
        {
            using (MD5 md5 = MD5.Create())
            {
                byte[] inputBytes = Encoding.ASCII.GetBytes(senha);
                byte[] hashBytes = md5.ComputeHash(inputBytes);
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("X2"));
                }
                return sb.ToString();
            }
        }

        public bool ValidarCpf()
        {
            int[] multiplicador1 = new int[9] { 10, 9, 8, 7, 6, 5, 4, 3, 2 };
            int[] multiplicador2 = new int[10] { 11, 10, 9, 8, 7, 6, 5, 4, 3, 2 };
            var cpfFormatado = Cpf.Trim().Replace(".", "").Replace("-", "");
            if (cpfFormatado.Length != 11)
                return false;
            for (int j = 0; j < 10; j++)
                if (j.ToString().PadLeft(11, char.Parse(j.ToString())) == cpfFormatado)
                    return false;
            string tempCpf = cpfFormatado.Substring(0, 9);
            int soma = 0;
            for (int i = 0; i < 9; i++)
                soma += int.Parse(tempCpf[i].ToString()) * multiplicador1[i];
            int resto = soma % 11;
            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;
            string digito = resto.ToString();
            tempCpf = tempCpf + digito;
            soma = 0;
            for (int i = 0; i < 10; i++)
                soma += int.Parse(tempCpf[i].ToString()) * multiplicador2[i];
            resto = soma % 11;
            if (resto < 2)
                resto = 0;
            else
                resto = 11 - resto;
            digito = digito + resto.ToString();
            return cpfFormatado.EndsWith(digito);
        }

        public void SenhaPadrao()
        {
            if (string.IsNullOrEmpty(Cpf)) throw new Exception("Não foi possível gerar uma senha padrão para este usuário!");
            var cpfSomenteNumeros = Regex.Replace(Cpf, "[^0-9]", "");
            Senha = GerarMd5(cpfSomenteNumeros);
        }

        public void Atualizar(Funcionario model)
        {
            Nome = model.Nome;
            Perfil = model.Perfil;
        }

        public void InverterAtivo()
        {
            Ativo = !Ativo;
        }

        public static Funcionario FuncionarioLogado()
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Funcionario>(HttpContext.Current.User.Identity.Name);           
        }

        public Collection<Movimentacao> Movimentacoes { get; set; }

        [ScriptIgnore]
        public Collection<Tarefa> TarefasCriadas { get; set; }

        [ScriptIgnore]
        public Collection<Tarefa> TarefasResponsaveis { get; set; }

        public Collection<JustificativaTarefa> JustificativasTarefas { get; set; }
    }
}

Advogado/Controllers/FuncionarioController.cs
using Advogado.Data;
using Advogado.Helpers;
using Advogado.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Advogado.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class FuncionarioController : Controller
    {
        private readonly MainContext _db = new MainContext();

        public ActionResult Index()
        {
            var list = _db.Funcionarios.ToList();
            return View(list);
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Novo(Funcionario model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                var cpfJaExiste = _db.Funcionarios.Any(x => x.Cpf == model.Cpf);
                if (cpfJaExiste) throw new Exception("O CPF informado já foi cadastrado!");
                var cpfValido = model.ValidarCpf();
                if (!cpfValido) throw new Exception("O CPF informado não é um CPF válido!");
                model.Ativo = true;
                model.SenhaPadrao();
                _db.Funcionarios.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _db.Funcionarios.Find(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Funcionario model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                var novo = _db.Funcionarios.Find(model.FuncionarioId);
                novo.Atualizar(model);
                _db.Entry(novo).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                var model = _db.Funcionarios.Find(id);
                model.InverterAtivo();
                _db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }
    }
}

Advogado/Views/Funcionario/Editar.cshtml
@model Advogado.Models.Funcionario
@{
    ViewBag.Title = "Editar Funcionário";
}

<div class="row small-spacing">
    <div class="col-lg-12 col-xs-12">
        <div class="box-content card white">
            <h4 class="box-title">@ViewBag.Title</h4>
            <div class="card-content">
                @using (Html.BeginForm("Editar", "Funcionario", FormMethod.Post, new { @class = "form" }))
                {
                    @Html.HiddenFor(m => m.FuncionarioId)
                    @Html.Partial("_Form")
                }
            </div>
        </div>
    </div>
</div>

Advogado/Views/Funcionario/Index.cshtml
@using Advogado.Models
@model IEnumerable<Funcionario>
@{
    ViewBag.Title = "Funcionários";
}

@section styles
{
    <link rel="stylesheet" href="~/Assets/plugin/datatables/media/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/plugin/datatables/extensions/Responsive/css/responsive.bootstrap.min.css">
}

@section scripts
{
    <script src="~/Assets/plugin/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/Assets/plugin/datatables/media/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Assets/plugin/datatables/extensions/Responsive/js/responsive.bootstrap.min.js"></script>
    <script src="~/Assets/scripts/datatables.demo.js"></script>
}

<div class="col-xs-12">
    <div class="box-content">
        <h4 class="box-title">@ViewBag.Title</h4>
        <div class="dropdown js__drop_down">
            <a href="@Url.Action("Novo")" class="btn btn-primary btn-circle btn-sm waves-effect waves-light"><i class="ico fa fa-plus"></i></a>
        </div>
        @Html.Partial("_Tabela")
    </div>
</div>

Advogado/Views/Funcionario/Novo.cshtml
@model Advogado.Models.Funcionario
@{
    ViewBag.Title = "Novo Funcionário";
}

<div class="row small-spacing">
    <div class="col-lg-12 col-xs-12">
        <div class="box-content card white">
            <h4 class="box-title">@ViewBag.Title</h4>
            <div class="card-content">
                @using (Html.BeginForm("Novo", "Funcionario", FormMethod.Post, new { @class = "form" }))
                {
                    @Html.Partial("_Form")
                }
            </div>
        </div>
    </div>
</div>

Advogado/Views/Funcionario/_Form.cshtml
@model Advogado.Models.Funcionario

@Html.AntiForgeryToken()

<div class="form-group col-md-12">
    @Html.LabelFor(m => m.Nome)
    @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", placeholder = "Informe o nome completo" })
    @Html.ValidationMessageFor(m => m.Nome)
</div>

@if (Model != null)
{
    <div class="form-group col-md-6">
        @Html.LabelFor(m => m.Cpf)
        @Html.TextBoxFor(m => m.Cpf, new { @class = "form-control cpf", placeholder = "Informe o CPF", @readonly="" })
        @Html.ValidationMessageFor(m => m.Cpf)
    </div>
}
else
{
    <div class="form-group col-md-6">
        @Html.LabelFor(m => m.Cpf)
        @Html.TextBoxFor(m => m.Cpf, new { @class = "form-control cpf", placeholder = "Informe o CPF" })
        @Html.ValidationMessageFor(m => m.Cpf)
    </div>
}

<div class="form-group col-md-6">
    @Html.LabelFor(m => m.Perfil)
    @Html.EnumDropDownListFor(m => m.Perfil, "Selecione...", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Perfil)
</div>

<div class="form-group col-md-12">
    <button type="submit" class="btn btn-primary btn-sm waves-effect waves-light">Salvar</button>
</div>

Advogado/Views/Funcionario/_Tabela.cshtml
@using Advogado.Models
@model IEnumerable<Funcionario>

<table id="example" class="table table-responsive table-striped table-bordered display" style="width:100%">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Perfil</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr @{ if (!item.Ativo) { @Html.Raw("style=\"background-color: #fdeef2\"")  ; } }>
                <td>@item.Nome</td>
                <td>@item.Cpf</td>
                <td>@item.Perfil</td>
                <td class="text-nowrap" width="10">
                    <a class="btn btn-circle btn-info btn-sm" title="Editar" href="@Url.Action("Editar", new { id = item.FuncionarioId })" data-togle="tooltip">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-circle @(item.Ativo ? "btn-warning" : "btn-success") btn-sm" title="@(item.Ativo ? "Desativar" : "Ativar")" btn-sm" href="@Url.Action("Remover", new { id = item.FuncionarioId })" data-togle="tooltip">
                        <i class="@(item.Ativo ? "fa fa-close" : "fa fa-check")" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>