Advogado/Models/Caso.cs
using System;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace Advogado.Models
{
    public class Caso
    {
        public int CasoId { get; set; }

        public string Protocolo => $"{CasoId}";

        public DateTime DataAbertura { get; set; }

        public SituacaoCaso SituacaoCaso { get; set; }

        [Display(Name = "Tipo de benefício")]
        public int TipoBeneficioId { get; set; }
        public TipoBeneficio TipoBeneficio { get; set; }

        public int ClienteId { get; set; }
        public Cliente Cliente { get; set; }

        [Display(Name = "Representante legal")]
        public int? RepresentanteLegalId { get; set; }
        public Cliente RepresentanteLegal { get; set; }

        public bool Ativo { get; set; }

        public string DataEmissao => $"{DateTime.Now.ToString("M")} de {DateTime.Now.Year}";

        public string RepresentanteLegalNome => RepresentanteLegal != null ? RepresentanteLegal.Nome : "Sem representante";

        public Collection<Arquivo> Arquivos { get; set; }
        public Collection<Resposta> Respostas { get; set; }
        public Collection<Movimentacao> Movimentacoes { get; set; }
        public Collection<GrupoFamiliar> GruposFamiliares { get; set; } 
        
        public Collection<Tarefa> Tarefas { get; set; }

        public int TotalTarefasAtrasadas => Tarefas != null ? Tarefas.Where(x => x.Finalizada == false && x.DataExpiracao < DateTime.Now).Count() : 0;

        public void RemoverTarefasEmDias()
        {
            var tarefasAtrasados = Tarefas.Where(x => x.Finalizada == false && x.DataExpiracao < DateTime.Now);
            Tarefas = new Collection<Tarefa>(tarefasAtrasados.ToList());
        }

        public void AtualizarCaso(Caso model)
        {
            TipoBeneficioId = model.TipoBeneficioId;
            RepresentanteLegalId = model.RepresentanteLegalId;
        }

        public void AtualizarCliente(Caso model)
        {
            Cliente.Atualizar(model.Cliente);           
        }       

        public void InverterAtivo()
        {
            Ativo = !Ativo;
        }

        #region Não mapeados       

        [NotMapped]
        public string Nome { get; set; }

        [NotMapped]
        public string Cpf { get; set; }

        [NotMapped]
        public DateTime DataNascimento { get; set; }

        [NotMapped]
        public string GrauParentesco { get; set; }
        #endregion
    }
}

Advogado/Controllers/CasoController.cs
using Advogado.Data;
using Advogado.Helpers;
using Advogado.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Advogado.Controllers
{
    [Authorize(Roles = "Administrador, Secretaria")]
    public class CasoController : Controller
    {
        private readonly MainContext _db = new MainContext();

        public ActionResult Index()
        {
            var list = _db.Casos.OrderByDescending(x => x.DataAbertura).Include(x => x.Cliente).Include(x => x.TipoBeneficio).ToList();
            return View(list);
        }

        public ActionResult Novo()
        {
            ViewBag.Responsaveis = _db.Funcionarios.ToList();
            return View();
        }

        public ActionResult Editar(int id)
        {
            ViewBag.Responsaveis = _db.Funcionarios.ToList();
            return View(new Caso { CasoId = id });
        }

        public void ValidarEstrangeiro(Caso model)
        {
            if (model.Cliente.ClienteEstrangeiro == true)
            {
                if (string.IsNullOrEmpty(model.Cliente.DocumentoIdentificacaoEstrangeiro)) throw new Exception("Documento do estrangeiro não preenchido!");
            }
            else
            {
                if (string.IsNullOrEmpty(model.Cliente.Rg)) throw new Exception("RG não preenchido!");
                if (model.Cliente.OrgaoExpedidorRg == 0) throw new Exception("Orgão expedidor do RG não preenchido!");
                if (model.Cliente.EstadoOrgaoExpedidor == 0) throw new Exception("Estado emissor do RG não preenchido!");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarCasoComDadosPessoais(Caso model)
        {
            try
            {
                ValidarEstrangeiro(model);
                ModelState.Remove("Nome");
                ModelState.Remove("Cpf");
                ModelState.Remove("DataNascimento");
                ModelState.Remove("GrauParentesco");
                if (model.CasoId == 0) ModelState.Remove("CasoId");
                if (model.CasoId != 0) ModelState.Remove("Cliente.Cpf");
                if (model.ClienteId != 0) ModelState.Remove("Cliente.Cpf");
                if (!ModelState.IsValid) throw new Exception("Preencha todos os campos corretamente!");
                if (model.ClienteId == 0 && !model.Cliente.ValidarCpf()) throw new Exception("O CPF informado é inválido!");
                if (model.CasoId == 0)
                {
                    var cliente = model.ClienteId != 0 ? _db.Clientes.Find(model.ClienteId) : null;

                    if (model.ClienteId != 0)
                    {                       
                        cliente.Atualizar(model.Cliente);
                        _db.Entry(cliente).State = EntityState.Modified;
                        model.Cliente = null;
                    }

                    model.DataAbertura = DateTime.Now;
                    model.SituacaoCaso = SituacaoCaso.Pendente;
                    model.Ativo = true;

                    var tarefas = new Collection<Tarefa>
                    {
                        new Tarefa
                        {
                            Titulo = $"Preencher todo o questionário do caso para o cliente {(cliente != null ? cliente.Nome : model.Cliente.Nome)}",
                            Descricao = "Esta tarefa será finalizada quando o questionário do caso for completado",
                            DataCriacao = DateTime.Now,
                            DataExpiracao = DateTime.Now.AddDays(PrazosConfig.PrazoDiasEntregaQuestionario),
                            TipoTarefa = TipoTarefa.EntregaQuestionario                            
                        },
                        new Tarefa
                        {
                            Titulo = $"Anexar toda a documentação ao caso do cliente {(cliente != null ? cliente.Nome : model.Cliente.Nome)}",
                            Descricao = "Esta tarefa será finalizada quando toda a documentação do caso for anexada",
                            DataCriacao = DateTime.Now,
                            DataExpiracao = DateTime.Now.AddDays(PrazosConfig.PrazoDiasEntregaDocumentacao),
                            TipoTarefa = TipoTarefa.EntregaDocumentacao
                        },
                        new Tarefa
                        {
                            Titulo = $"Protocolar o processo do cliente {(cliente != null ? cliente.Nome : model.Cliente.Nome)} administrativamente no INSS",
                            Descricao = "Por favor finalizar esta tarefa quando estiver pronta",
                            DataCriacao = DateTime.Now,
                            DataExpiracao = DateTime.Now.AddDays(PrazosConfig.PrazoDiasProtocoloAdministrativo),
                            TipoTarefa = TipoTarefa.ProtocoloAdministrativo
                        },
                        new Tarefa
                        {
                             Titulo = $"Protocolar o processo do cliente {(cliente != null ? cliente.Nome : model.Cliente.Nome)} judicialmente",
                            Descricao = "Por favor finalizar esta tarefa quando estiver pronta",
                            DataCriacao = DateTime.Now,
                            DataExpiracao = DateTime.Now.AddDays(PrazosConfig.PrazoDiasProtocoloJudicial),
                            TipoTarefa = TipoTarefa.ProtocoloJudicial
                        }
                    };

                    model.Tarefas = tarefas;
                    var retorno = _db.Casos.Add(model);
                    _db.SaveChanges();
                    return Json(new { Success = "Os dados pessoais foram salvos com sucesso!", retorno.CasoId }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var novo = _db.Casos.Include(x => x.Cliente).Include(x => x.GruposFamiliares).First(x => x.CasoId == model.CasoId);
                    BalancearListaGruposFamiliares(novo, model);
                    novo.AtualizarCaso(model);
                    novo.AtualizarCliente(model);
                    _db.Entry(novo).State = EntityState.Modified;
                    _db.SaveChanges();
                    return Json(new { Success = "Os dados pessoais foram alterados com sucesso!", novo.CasoId, novo.ClienteId }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { Error = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarCasoComQuestionario(List<Resposta> Respostas, int casoId)
        {
            try
            {
                var respostasNovas = Respostas.Where(x => x.RespostaId == 0);
                var respostasExistentes = Respostas.Where(x => x.RespostaId != 0);
                respostasNovas = respostasNovas.Where(x => x.RespostaDescritiva?.Trim() != "" || x.AlternativaId != 0 || (x.AlternativasIds != null && x.AlternativasIds.Any())).ToList();
                respostasExistentes = respostasExistentes.Where(x => x.RespostaDescritiva?.Trim() != "" || x.AlternativaId != 0 || (x.AlternativasIds != null && x.AlternativasIds.Any())).ToList();
                foreach (var respostaNova in respostasNovas)
                {
                    if (respostaNova.AlternativaId != 0)
                    {
                        respostaNova.Alternativas = new Collection<Alternativa>
                        {
                            _db.Alternativas.Find(respostaNova.AlternativaId)
                        };
                    }
                    if (respostaNova.AlternativasIds != null && respostaNova.AlternativasIds.Any())
                    {
                        respostaNova.Alternativas = new Collection<Alternativa>();
                        foreach (var alternativaId in respostaNova.AlternativasIds)
                        {
                            respostaNova.Alternativas.Add(_db.Alternativas.Find(alternativaId));
                        }
                    }
                }
                foreach (var respostaExistente in respostasExistentes)
                {
                    if (respostaExistente.AlternativaId != 0)
                    {
                        respostaExistente.Alternativas = new Collection<Alternativa>
                        {
                            _db.Alternativas.Find(respostaExistente.AlternativaId)
                        };
                    }
                    if (respostaExistente.AlternativasIds != null && respostaExistente.AlternativasIds.Any())
                    {
                        respostaExistente.Alternativas = new Collection<Alternativa>();
                        foreach (var alternativaId in respostaExistente.AlternativasIds)
                        {
                            respostaExistente.Alternativas.Add(_db.Alternativas.Find(alternativaId));
                        }
                    }
                }
                if (respostasNovas != null && respostasNovas.Any()) _db.Respostas.AddRange(respostasNovas);
                if (respostasExistentes != null && respostasExistentes.Any())
                {
                    foreach (var respostaNova in respostasExistentes)
                    {
                        var pergunta = _db.Perguntas.Find(respostaNova.PerguntaId);
                        if (pergunta.MultiplaAlternativa == false)
                        {
                            var respostaAntiga = _db.Respostas.Find(respostaNova.RespostaId);

Advogado/Controllers/ClienteController.cs
using Advogado.Data;
using Advogado.Helpers;
using Advogado.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Advogado.Controllers
{
    [Authorize(Roles = "Administrador, Secretaria")]
    public class ClienteController : Controller
    {
        private readonly MainContext _db = new MainContext();

        public ActionResult Index()
        {
            var list = _db.Clientes.ToList();
            return View(list);
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Novo(Cliente model)
        {
            try
            {
                ValidarEstrangeiro(model);
                if (!ModelState.IsValid) throw new Exception();
                if (!model.ValidarCpf()) throw new Exception("O CPF informado é inválido!");
                var cpfJaExiste = _db.Clientes.Any(x => x.Cpf == model.Cpf);
                if (cpfJaExiste) throw new Exception("O CPF informado já foi utilizado!");
                _db.Clientes.Add(model);
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _db.Clientes.Find(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Cliente model)
        {
            try
            {
                ValidarEstrangeiro(model);
                ModelState.Remove("Cpf");
                if (!ModelState.IsValid) throw new Exception();
                var novo = _db.Clientes.Find(model.ClienteId);
                novo.Atualizar(model);
                _db.Entry(novo).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                //Cliente para excluir
                var cliente = _db.Clientes.Find(id);

                //Casos para excluir
                var casos = _db.Casos.Where(x => x.ClienteId == id);

                //Arquivos do caso para excluir
                var arquivosDoCaso = _db.Arquivos.Where(x => x.Caso.ClienteId == id);

                //Movimentações do caso para excluir
                var movimentacoesDoCaso = _db.Movimentacoes.Where(x => x.Caso.ClienteId == id);

                //Grupo familiar do caso para excluir
                var grupoFamiliarDoCaso = _db.GruposFamiliares.Where(x => x.Caso.ClienteId == id);

                //Tarefas do caso para excluir
                var tarefasDoCaso = _db.Tarefas.Where(x => x.Caso.ClienteId == id);

                //Justificativa das tarefas do caso para excluir
                var justificativasTarefasDoCaso = _db.JustificativasTarefas.Where(x => x.Tarefa.Caso.ClienteId == id);

                //Respostas do caso para excluir
                var respostasDoCaso = _db.Respostas.Include(x => x.Alternativas).Where(x => x.Caso.ClienteId == id);

                _db.Arquivos.RemoveRange(arquivosDoCaso);

                _db.Movimentacoes.RemoveRange(movimentacoesDoCaso);

                _db.GruposFamiliares.RemoveRange(grupoFamiliarDoCaso);

                _db.JustificativasTarefas.RemoveRange(justificativasTarefasDoCaso);

                _db.Tarefas.RemoveRange(tarefasDoCaso);

                _db.Respostas.RemoveRange(respostasDoCaso);

                _db.Casos.RemoveRange(casos);

                _db.Entry(cliente).State = EntityState.Deleted;

                _db.SaveChanges();

                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }

        public void ValidarEstrangeiro(Cliente model)
        {
            if (model.ClienteEstrangeiro == true)
            {
                if (string.IsNullOrEmpty(model.DocumentoIdentificacaoEstrangeiro)) throw new Exception("Documento do estrangeiro não preenchido!");
            }
            else
            {
                if (string.IsNullOrEmpty(model.Rg)) throw new Exception("RG não preenchido!");
                if (model.OrgaoExpedidorRg == 0) throw new Exception("Orgão expedidor do RG não preenchido!");
                if (model.EstadoOrgaoExpedidor == 0) throw new Exception("Estado emissor do RG não preenchido!");
            }
        }
    }
}

Advogado/Views/Caso/Editar.cshtml
@model Advogado.Models.Caso
@{
    ViewBag.Title = "Editar Caso";
}

@section styles
{
    <link rel="stylesheet" href="~/Assets/plugin/bootstrap-select/css/bootstrap-select.css" />
    <style>
        .box-content.card .dropdown {
            top: 0px !important;
        }
    </style>

    <!-- FullCalendar -->
    <link rel="stylesheet" href="~/Assets/plugin/fullcalendar/fullcalendar.min.css">
    <link rel="stylesheet" href="~/Assets/plugin/fullcalendar/fullcalendar.print.css" media='print'>

    <!-- Datepicker -->
    <link rel="stylesheet" href="~/Assets/plugin/datepicker/css/bootstrap-datepicker.min.css">
}

@section scripts
{
    <script src="~/Assets/plugin/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="~/Assets/plugin/bootstrap-select/js/i18n/defaults-pt_BR.js"></script>
    <script src="~/Assets/plugin/pdfmake/pdfmake.js"></script>
    <script src="~/Assets/plugin/pdfmake/vfs_fonts.js"></script>
    <script src="~/Assets/scripts/caso.js"></script>
    <script src="~/Assets/scripts/impressao.js"></script>
    <script src="~/Assets/scripts/estrangeiro.js"></script>

    <!-- Jquery UI -->
    <script src="~/Assets/plugin/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/Assets/plugin/jquery-ui/jquery.ui.touch-punch.min.js"></script>

    <!-- FullCalendar -->
    <script src="~/Assets/plugin/moment/moment.js"></script>
    <script src="~/Assets/plugin/fullcalendar/fullcalendar.min.js"></script>
    <script src="~/Assets/plugin/fullcalendar/locale/pt-br.js"></script>

    <!-- Datepicker -->
    <script src="~/Assets/plugin/datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Assets/plugin/datepicker/locales/bootstrap-datepicker.pt-BR.min.js"></script>

    <script src="~/Assets/scripts/tarefas.js"></script>
}

@section modal
{
    @Html.Partial("_NovoAcompanhamento", new Advogado.Models.Movimentacao())
    @Html.Partial("_NovaTarefa", new Advogado.Models.Tarefa())
    @Html.Partial("_FinalizarTarefa", new Advogado.Models.Tarefa())
    @Html.Partial("_AlterarResponsavel", new Advogado.Models.Tarefa())
    @Html.Partial("_AlterarPrazo", new Advogado.Models.Tarefa())
    @Html.Partial("_AnexarDocumento", new Advogado.Models.Arquivo())
    @Html.Partial("_ParametrosContrato")
    <div data-url="@Url.Action("DetalhesTarefa", "Tarefa")" class="modal fade" id="modalDetalhesTarefa" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
}

<div class="col-md-12 col-xs-12">
    <div class="box-content">
        <h4 class="box-title">@ViewBag.Title</h4>
        <ul class="nav nav-tabs">
            <li id="menu-dadospessoais" class="active" data-caso-id="@Model.CasoId"><a data-toggle="tab" href="#dadospessoais">Dados Pessoais</a></li>
            <li id="menu-questionario" class="disabled"><a data-toggle="tab" href="#questionario">Questionário</a></li>
            <li id="menu-documentos" class="disabled"><a data-toggle="tab" href="#documentos">Documentos Exigidos</a></li>
            <li id="menu-impressao" class="disabled"><a data-toggle="tab" href="#impressao">Impressões</a></li>
            <li id="menu-acompanhamento" class="disabled"><a data-toggle="tab" href="#acompanhamento">Acompanhamento</a></li>
            <li id="menu-tarefas" class="disabled"><a data-toggle="tab" href="#tarefas">Tarefas</a></li>
        </ul>
        <div class="tab-content">
            <div id="dadospessoais" class="tab-pane fade in active" data-url="@Url.Action("DadosPessoais", "Caso")">
                <div class="row">
                    @using (Html.BeginForm("SalvarCasoComDadosPessoais", "Caso", FormMethod.Post, new { @class = "form", id = "frmSalvarCasoComDadosPessoais" }))
                    {
                        <div id="frm-conteudo-dadospessoais"></div>
                    }
                </div>
            </div>
            <div id="questionario" class="tab-pane fade disabled" data-url="@Url.Action("Questionario", "Caso")">
                @using (Html.BeginForm("SalvarCasoComQuestionario", "Caso", FormMethod.Post, new { @class = "form", id = "frmSalvarCasoComQuestionario" }))
                {
                    <div id="frm-conteudo-questionario" class="row"></div>
                }
            </div>
            <div id="documentos" class="tab-pane fade disabled" data-url="@Url.Action("Documentos", "Caso")">
                <div id="frm-conteudo-documento" class="row"></div>
            </div>
            <div id="impressao" class="tab-pane fade disabled">
                <div id="frm-conteudo-impressao" class="row">
                    @Html.Partial("_Impressao")
                </div>
            </div>
            <div id="acompanhamento" class="tab-pane fade disabled" data-url="@Url.Action("Movimentos", "Caso")">
                <div id="frm-conteudo-acompanhamento" class="row"></div>
            </div>
            <div id="tarefas" class="tab-pane fade disabled" data-url="@Url.Action("Tarefas", "Caso")">
                <div id="frm-conteudo-tarefas" class="row">
                    @Html.Partial("_Tarefas")
                </div>
            </div>
        </div>
    </div>
</div>

Advogado/Views/Caso/_GruposFamiliares.cshtml
@model Advogado.Models.Caso

<div class="form-group col-md-12" style="margin-bottom: 0px">
    <h4>Grupo Familiar</h4>
    <hr class="my-4">
</div>


<div class="lista-gruposfamiliares form-group col-md-12">
    @Html.Action("ListaGruposFamiliares", "Caso", new { casoGrupoFamiliar = Model })
</div>

Advogado/Views/Caso/_Impressao.cshtml
@{
    ViewBag.Title = "_Impressoes";
}

<div class="form-group col-md-12" style="margin-bottom: 0px">
    <h4>Documentos a serem impressos</h4>
    <hr class="my-4">
</div>

<div class="col-md-12">
    <table id="impressao" class="table table-bordered">
        <thead>
            <tr>
                <th>Documento a ser impresso</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr class="active" id="impressao-procuracao" data-url="@Url.Action("ImprimirProcuracao", "Caso")">
                <td>Procuração</td>
                <td class="text-nowrap" width="10">
                    <a class="btn btn-circle btn-info btn-sm" title="Imprimir documento" href="#" onclick="Impressao.imprimirProcuracao()">
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            <tr class="active" id="impressao-contrato" data-url="@Url.Action("ImprimirContrato", "Caso")">
                <td>Contrato</td>
                <td class="text-nowrap" width="10">
                    <a class="btn btn-circle btn-info btn-sm" title="Imprimir documento" href="#" onclick="Impressao.parametrosContrato()">
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            <tr class="active" id="impressao-ficha-atendimento" data-url="@Url.Action("ImprimirFichaAtendimento", "Caso")">
                <td>Ficha de atendimento</td>
                <td class="text-nowrap" width="10">
                    <a class="btn btn-circle btn-info btn-sm" title="Imprimir documento" href="#" onclick="Impressao.imprimirFichaAtendimento()">
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            <tr class="active" id="impressao-declaracao-residencia" data-url="@Url.Action("ImprimirDeclaracaoResidencia", "Caso")">
                <td>Declaração de residência</td>
                <td class="text-nowrap" width="10">
                    <a class="btn btn-circle btn-info btn-sm" title="Imprimir documento" href="#" onclick="Impressao.imprimirDeclaracaoResidencia()">
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

Advogado/Views/Caso/_NovoAcompanhamento.cshtml
@model Advogado.Models.Movimentacao

<div class="modal fade" id="modalNovoAcompanhamento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Novo acompanhamento</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("SalvarCasoComMovimentacao", "Caso", FormMethod.Post, new { @class = "form", id = "frmSalvarCasoComMovimentacao", enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(m => m.CasoId)
                    <div class="row">
                        <div class="form-group col-md-12">
                            @Html.LabelFor(m => m.TipoMovimento) <label style="color: red" title="Este campo é obrigatório">*</label>
                            @Html.EnumDropDownListFor(m => m.TipoMovimento, "Selecione...", new { @class = "form-control", required = "" })
                            @Html.ValidationMessageFor(m => m.TipoMovimento)
                        </div>
                        <div class="form-group col-md-12">
                            @Html.LabelFor(m => m.Descricao) <label style="color: red" title="Este campo é obrigatório">*</label>
                            @Html.TextAreaFor(m => m.Descricao, new { @class = "form-control", placeholder = "Informe os detalhes deste acompanhamento", required = "" })
                            @Html.ValidationMessageFor(m => m.Descricao)
                        </div>
                        <div class="col-md-12" id="div-modelo-arquivo">
                            <label>Arquivo</label> <label style="color: blue" title="Este campo é opcional">Opcional</label>
                            <input type="file" id="ArquivoBinario" name="ArquivoBinario">
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-sm waves-effect waves-light" onclick="$('#frmSalvarCasoComMovimentacao').submit()">Salvar</button>
                <button type="button" class="btn btn-default btn-sm waves-effect waves-light" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>